bugfix: unpack requires exactly length of data
Traceback (most recent call last):
  File "/home/jaime/source/dae-sdk/dae/commands/log.py", line 40, in _main
    lines = ws.recv()
  File "/home/jaime/source/dae-sdk/venv/src/websocket-client/websocket.py", line 531, in recv
    opcode, data = self.recv_data()
  File "/home/jaime/source/dae-sdk/venv/src/websocket-client/websocket.py", line 543, in recv_data
    frame = self.recv_frame()
  File "/home/jaime/source/dae-sdk/venv/src/websocket-client/websocket.py", line 579, in recv_frame
    length = struct.unpack("!H", length_data)[0]
error: unpack requires a string argument of length 2