_http.py: fix windows proxy error due to socktype
Resolves #426
When running on windows 10 with a proxy, there is a connect error:
_on_error: exception Socket type must be stream or datagram, not 0

This commit fixes that issue.

Signed-off-by: Paul Barrette <paulbarrette@gmail.com>